name: Deploy Archi Report
description: Deploy Archimate model as static report site
author: WoozyMasta, kagbe.leviy@gmail.com
branding:
  icon: book-open
  color: blue
runs:
  using: docker
  image: Dockerfile
