name: Create Release
on:
  push:
    tags:
      - "*.**"

jobs:
  build_and_push:
    name: Build and push container image
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: write
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2

      - name: Set env
        id: env
        run: |
          echo ::set-output name=tag::${GITHUB_REF#refs/tags/}
          echo ::set-output name=repository::${GITHUB_REPOSITORY,,}

      - name: Log in to GitHub Container registry
        if: github.event_name != 'pull_request'
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Log in to Docker Hub Container registry
        if: github.event_name != 'pull_request'
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push container image
        uses: docker/build-push-action@v4
        with:
          context: .
          file: ./Dockerfile
          push: ${{ github.event_name != 'pull_request' }}
          tags: |
            ghcr.io/${{ github.repository }}:${{ steps.env.outputs.tag }}
            ghcr.io/${{ github.repository }}:latest
            docker.io/${{ steps.env.outputs.repository }}:${{ steps.env.outputs.tag }}
            docker.io/${{ steps.env.outputs.repository }}:latest
          build-args: STATIC_BASH_VERSION=${{ steps.static-bash.outputs.release }}

      - name: Build and push rootless container image
        uses: docker/build-push-action@v4
        with:
          context: .
          file: ./Dockerfile.rootless
          push: ${{ github.event_name != 'pull_request' }}
          tags: |
            ghcr.io/${{ github.repository }}:${{ steps.env.outputs.tag }}-rootless
            ghcr.io/${{ github.repository }}:latest-rootless
            docker.io/${{ steps.env.outputs.repository }}:${{ steps.env.outputs.tag }}-rootless
            docker.io/${{ steps.env.outputs.repository }}:latest-rootless
          build-args: |
            ARCHIMATE_CI_VERSION=${{ steps.env.outputs.tag }}

      - name: Create Release
        id: create_release
        uses: ncipollo/release-action@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          body: |
            GitHub Action [Deploy Archi Report ${{ steps.env.outputs.tag }}](https://github.com/marketplace/actions/deploy-archi-report?version=${{ steps.env.outputs.tag }})

            Container images:

            ${{ github.repository }}:**${{ steps.env.outputs.tag }}**

            * `docker pull ghcr.io/${{ github.repository }}:${{ steps.env.outputs.tag }}`
            * `docker pull docker.io/${{ steps.env.outputs.repository }}:${{ steps.env.outputs.tag }}`

            ${{ github.repository }}:**${{ steps.env.outputs.tag }}-rootless**

            * `docker pull ghcr.io/${{ github.repository }}:${{ steps.env.outputs.tag }}-rootless`
            * `docker pull docker.io/${{ steps.env.outputs.repository }}:${{ steps.env.outputs.tag }}-rootless`

            > [Changelog](https://github.com/WoozyMasta/archimate-ci-image/blob/master/CHANGELOG.md)

          draft: false
          prerelease: false
